export const wm = {
  colors: {
    background: "#f8f9ff",
    appBackground: "#f4f7fb",
    surface: "#ffffff",
    surfaceLow: "#eff4ff",
    surfaceContainer: "#e6eeff",
    surfaceHigh: "#dce9ff",
    surfaceHighest: "#d5e3fc",
    text: "#0d1c2e",
    textSecondary: "#454650",
    textMuted: "#64748b",
    primary: "#000c43",
    primaryContainer: "#16235a",
    secondary: "#0051d5",
    secondaryContainer: "#316bf3",
    border: "#d8e0ec",
    borderSubtle: "#e6ebf2",
    borderStrong: "#c6c5d1",
    success: "#16a34a",
    successBg: "#f0fdf4",
    successBorder: "#bbf7d0",
    focus: "#2563eb",
    focusBg: "#eff6ff",
    focusBorder: "#bfdbfe",
    break: "#f97316",
    breakBg: "#fff7ed",
    breakBorder: "#fed7aa",
    offline: "#64748b",
    offlineBg: "#f8fafc",
    offlineBorder: "#cbd5e1",
    privacyCollected: "#1d4ed8",
    privacyCollectedBg: "#eff6ff",
    privacyCollectedBorder: "#bfdbfe",
    privacyExcluded: "#15803d",
    privacyExcludedBg: "#f0fdf4",
    privacyExcludedBorder: "#bbf7d0",
    compliance: "#0f766e",
    complianceBg: "#f0fdfa",
    complianceBorder: "#99f6e4",
    warning: "#b45309",
    warningBg: "#fff7ed",
    warningBorder: "#fed7aa",
    infoText: "#1e3a8a",
    infoBg: "#eff6ff",
    infoBorder: "#bfdbfe",
    error: "#ba1a1a",
    errorBg: "#ffdad6",
    errorText: "#93000a",
  },
  status: {
    available: "#22c55e",
    busy: "#ef4444",
    focus: "#3b82f6",
    idle: "#f59e0b",
    break: "#f97316",
    offline: "#94a3b8",
    on_call: "#8b5cf6",
  },
  radius: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    "2xl": "24px",
    full: "9999px",
  },
  spacing: {
    1: "8px",
    2: "16px",
    3: "24px",
    4: "32px",
    5: "40px",
  },
  shadow: {
    card: "0 4px 20px rgba(15, 23, 42, 0.05)",
    elevated: "0 12px 32px rgba(15, 23, 42, 0.12)",
    overlay: "0 24px 72px rgba(15, 23, 42, 0.18)",
  },
  typography: {
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    pageTitle: "32px",
    sectionTitle: "20px",
    body: "14px",
    small: "12px",
  },
  border: {
    subtle: "1px solid #e6ebf2",
    default: "1px solid #d8e0ec",
    strong: "1px solid #c6c5d1",
  },
  zIndex: {
    map: 0,
    officeChrome: 20,
    officePanel: 35,
    officeDrawer: 42,
    officeControls: 45,
    officeModal: 60,
    modal: 100,
  },
  sizes: {
    topNavHeight: "64px",
    officeRailWidth: "72px",
    officeMiniMapWidth: "214px",
    officeMiniMapHeight: "138px",
    officeControlWidth: "52px",
    buttonHeight: "40px",
    inputHeight: "40px",
  },
} as const;

export const wmStyles = {
  page: {
    minHeight: "100vh",
    background: wm.colors.appBackground,
    color: wm.colors.text,
    fontFamily: wm.typography.fontFamily,
  },
  pageStack: {
    display: "grid",
    gap: wm.spacing[3],
  },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: wm.spacing[2],
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    gap: wm.spacing[2],
  },
  eyebrow: {
    margin: "0 0 8px",
    color: wm.colors.secondary,
    fontSize: "12px",
    fontWeight: 700,
    lineHeight: 1.2,
    letterSpacing: "0.01em",
    textTransform: "uppercase" as const,
  },
  pageTitle: {
    margin: "0 0 8px",
    color: wm.colors.text,
    fontSize: "32px",
    lineHeight: 1.25,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  },
  pageSubtitle: {
    margin: 0,
    color: wm.colors.textSecondary,
    fontSize: "16px",
    lineHeight: 1.6,
  },
  card: {
    border: `1px solid ${wm.colors.border}`,
    borderRadius: wm.radius.xl,
    background: wm.colors.surface,
    boxShadow: wm.shadow.card,
  },
  elevatedCard: {
    border: `1px solid ${wm.colors.border}`,
    borderRadius: wm.radius["2xl"],
    background: wm.colors.surface,
    boxShadow: wm.shadow.elevated,
  },
  primaryButton: {
    border: `1px solid ${wm.colors.secondary}`,
    borderRadius: wm.radius.md,
    background: wm.colors.secondary,
    color: "#ffffff",
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "20px",
    cursor: "pointer",
  },
  secondaryButton: {
    border: `1px solid ${wm.colors.primaryContainer}`,
    borderRadius: wm.radius.md,
    background: wm.colors.surface,
    color: wm.colors.primaryContainer,
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "20px",
    cursor: "pointer",
  },
  input: {
    border: `1px solid ${wm.colors.border}`,
    borderRadius: wm.radius.md,
    background: wm.colors.surface,
    color: wm.colors.text,
    fontSize: "14px",
  },
  notice: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    borderRadius: wm.radius.xl,
    padding: "12px 14px",
    fontSize: "14px",
    lineHeight: 1.45,
  },
  infoNotice: {
    border: `1px solid ${wm.colors.infoBorder}`,
    borderRadius: wm.radius.xl,
    background: wm.colors.infoBg,
    color: wm.colors.infoText,
  },
} as const;
