export const wm = {
  colors: {
    background: "#f6f7f2",
    appBackground: "#f6f7f2",
    surface: "#ffffff",
    surfaceLow: "#f1f3ef",
    surfaceContainer: "#e9ede8",
    surfaceHigh: "#dfe5e0",
    surfaceHighest: "#d3dbd6",
    text: "#080d22",
    textHeading: "#080d22",
    textSecondary: "#62697a",
    textMuted: "#7b8392",
    textSubtle: "#949ba5",
    primary: "#080d22",
    primaryContainer: "#121932",
    secondary: "#27e0a2",
    secondaryContainer: "#55e9b8",
    border: "#dde1db",
    borderSubtle: "#e9ece8",
    borderStrong: "#bfc8c3",
    success: "#17865c",
    successBg: "#ebf8f2",
    successBorder: "#9edbc4",
    focus: "#276ee8",
    focusBg: "#edf3ff",
    focusBorder: "#adc7f8",
    break: "#a6630f",
    breakBg: "#fff4dc",
    breakBorder: "#edca86",
    offline: "#737b88",
    offlineBg: "#f2f3f1",
    offlineBorder: "#cdd1cc",
    privacyCollected: "#13875f",
    privacyCollectedBg: "#ebf8f2",
    privacyCollectedBorder: "#9edbc4",
    privacyExcluded: "#c3423d",
    privacyExcludedBg: "#fff0ed",
    privacyExcludedBorder: "#efb4af",
    compliance: "#0d7454",
    complianceBg: "#ebf8f2",
    complianceBorder: "#9edbc4",
    warning: "#8b570b",
    warningBg: "#fff4dc",
    warningBorder: "#edca86",
    infoText: "#27466a",
    infoBg: "#eef4f7",
    infoBorder: "#b8cbd7",
    error: "#c3423d",
    errorBg: "#fff0ed",
    errorText: "#8f2825",
  },
  status: {
    available: "#1aae73",
    busy: "#e0504b",
    focus: "#276ee8",
    idle: "#c88a17",
    break: "#a6630f",
    offline: "#858c97",
    on_call: "#7656c9",
  },
  radius: {
    sm: "4px",
    md: "4px",
    lg: "6px",
    xl: "6px",
    "2xl": "8px",
    full: "9999px",
  },
  spacing: {
    1: "8px",
    2: "16px",
    3: "24px",
    4: "32px",
    5: "40px",
  },
  shadow: {
    card: "0 1px 2px rgba(8, 13, 34, 0.05)",
    elevated: "0 12px 32px rgba(8, 13, 34, 0.11)",
    overlay: "0 20px 52px rgba(8, 13, 34, 0.18)",
  },
  typography: {
    fontFamily: '"Graphik Web", Graphik, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    displayFontFamily: '"Graphik Web Semibold", "Graphik Web", Graphik, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    pageTitle: "34px",
    sectionTitle: "20px",
    body: "14px",
    small: "12px",
  },
  border: {
    subtle: "1px solid #e9ece8",
    default: "1px solid #dde1db",
    strong: "1px solid #bfc8c3",
  },
  zIndex: {
    map: 0,
    officeChrome: 20,
    officePanel: 35,
    officeDrawer: 42,
    officeControls: 45,
    officeModal: 60,
    modal: 100,
  },
  sizes: {
    topNavHeight: "64px",
    officeRailWidth: "64px",
    officeMiniMapWidth: "214px",
    officeMiniMapHeight: "138px",
    officeControlWidth: "52px",
    buttonHeight: "40px",
    inputHeight: "40px",
  },
} as const;

export const wmStyles = {
  page: {
    minHeight: "100vh",
    background: wm.colors.appBackground,
    color: wm.colors.text,
    fontFamily: wm.typography.fontFamily,
  },
  pageStack: {
    display: "grid",
    gap: wm.spacing[3],
  },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: wm.spacing[2],
    flexWrap: "wrap" as const,
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    gap: wm.spacing[2],
  },
  eyebrow: {
    margin: "0 0 8px",
    color: wm.colors.secondary,
    fontSize: "12px",
    fontWeight: 750,
    lineHeight: 1.2,
    letterSpacing: 0,
    textTransform: "uppercase" as const,
  },
  pageTitle: {
    margin: "0 0 8px",
    color: wm.colors.textHeading,
    fontSize: wm.typography.pageTitle,
    fontFamily: wm.typography.displayFontFamily,
    lineHeight: 1.15,
    fontWeight: 750,
    letterSpacing: 0,
  },
  pageSubtitle: {
    margin: 0,
    color: wm.colors.textSecondary,
    fontSize: "16px",
    lineHeight: 1.55,
  },
  card: {
    border: `1px solid ${wm.colors.border}`,
    borderRadius: wm.radius.xl,
    background: wm.colors.surface,
    boxShadow: wm.shadow.card,
  },
  elevatedCard: {
    border: `1px solid ${wm.colors.border}`,
    borderRadius: wm.radius["2xl"],
    background: wm.colors.surface,
    boxShadow: wm.shadow.elevated,
  },
  primaryButton: {
    border: `1px solid ${wm.colors.secondary}`,
    borderRadius: wm.radius.md,
    background: wm.colors.secondary,
    color: wm.colors.primary,
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "20px",
    cursor: "pointer",
  },
  secondaryButton: {
    border: `1px solid ${wm.colors.borderStrong}`,
    borderRadius: wm.radius.md,
    background: wm.colors.surface,
    color: wm.colors.primary,
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "20px",
    cursor: "pointer",
  },
  input: {
    border: `1px solid ${wm.colors.border}`,
    borderRadius: wm.radius.md,
    background: wm.colors.surface,
    color: wm.colors.text,
    fontSize: "14px",
  },
  notice: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    borderRadius: wm.radius.xl,
    padding: "12px 14px",
    fontSize: "14px",
    lineHeight: 1.45,
  },
  infoNotice: {
    border: `1px solid ${wm.colors.infoBorder}`,
    borderRadius: wm.radius.xl,
    background: wm.colors.infoBg,
    color: wm.colors.infoText,
  },
} as const;
